/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bubblesort_MainActivity */

#ifndef _Included_com_example_bubblesort_MainActivity
#define _Included_com_example_bubblesort_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bubblesort_MainActivity
 * Method:    bubbleSortC
 * Signature: ([Ljava/lang/Integer;)F
 */
JNIEXPORT jlong JNICALL Java_com_example_bubblesort_MainActivity_bubbleSortC
  (JNIEnv *, jobject, jintArray );

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_example_bubblesort_MainActivity_PlaceholderFragment */

#ifndef _Included_com_example_bubblesort_MainActivity_PlaceholderFragment
#define _Included_com_example_bubblesort_MainActivity_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
